sample_rate: 16000
repeat: 1
dropout: 0.0
normalize_trainscripts: false
separable: true
labels:
- ' '
- а
- б
- в
- г
- д
- е
- ё
- ж
- з
- и
- й
- к
- л
- м
- н
- о
- п
- р
- с
- т
- у
- ф
- х
- ц
- ч
- ш
- щ
- ъ
- ы
- ь
- э
- ю
- я
train_ds:
  manifest_filepath: /home/geripc/gitrepos/russian_asr/mozilla/ru/custom_train.json
  sample_rate: 16000
  labels:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
  batch_size: 16
  trim_silence: true
  normalize_transcripts: false
  max_duration: 16.7
  shuffle: true
  is_tarred: false
  tarred_audio_filepaths: null
  parser: base
  num_workers: 8
validation_ds:
  manifest_filepath: /home/geripc/gitrepos/russian_asr/mozilla/ru/test.json
  sample_rate: 16000
  labels:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
  batch_size: 16
  normalize_transcripts: false
  shuffle: false
  parser: base
  num_workers: 8
test_ds:
  manifest_filepath: /home/geripc/gitrepos/russian_asr/buriy_audiobooks_2_val/dev_manifest.json
  sample_rate: 16000
  labels:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
  batch_size: 16
  normalize_transcripts: false
  shuffle: false
  parser: base
  num_workers: 8
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  normalize: per_feature
  window_size: 0.02
  sample_rate: 16000
  window_stride: 0.01
  window: hann
  features: 64
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  stft_conv: false
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  rect_freq: 50
  rect_masks: 5
  rect_time: 120
encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 64
  activation: relu
  conv_mask: true
  jasper:
  - filters: 256
    repeat: 1
    kernel:
    - 33
    stride:
    - 2
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 1
    kernel:
    - 87
    stride:
    - 1
    dilation:
    - 2
    dropout: 0.0
    residual: false
    separable: true
  - filters: 1024
    repeat: 1
    kernel:
    - 1
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 1024
  num_classes: 34
  vocabulary:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
optim:
  name: novograd
  lr: 0.0001
  betas:
  - 0.8
  - 0.5
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    monitor: val_loss
    reduce_on_plateau: false
    warmup_steps: 100
    warmup_ratio: null
    min_lr: 0.0
    last_epoch: -1
target: nemo.collections.asr.models.ctc_models.EncDecCTCModel
